Done with api integration of issue page
learn-opensource/learn-opensource.github.io pull request #16
Opened 2020-10-21 16:20 UTC by utkarsh4321

Hii @sachin-duhan26 thanks for this great opportunity. I did API integration according to your requirement as I understand. So Please review this PR. If you found any problem with this please tell me so I will try to fix asap.

2020-10-21 16:45 UTC, sachin-duhan26 requested changes
Hello @utkarsh4321 
You did a **Terrific Job** ❤️  when it comes to writing readable code 💯 . I believe we need some small changes and a more generalized solution for the issue.html page.

Kindly find the detailed review of the #16
Thanks and cheers 🍻

2020-10-21 16:45 UTC, sachin-duhan26 commented on issues.html
> -        AOS.init();
replace AOS config with the code snippet given below ⬇️ 
```js
    <script>
        AOS.init({
            duration: 700,
            offset: 180
        });
    </script>
```

2020-10-21 16:45 UTC, sachin-duhan26 commented on js/controller/getReposIssues.js
> +const repos = {
we are looking forward to displaying all issues that are there for [learn-opensource](http://learn-opensource.github.io/).
- Do not 🚫  limit the issue only to learn-opensource.github.io repo only!

2020-10-21 16:45 UTC, sachin-duhan26 commented on js/main.js
> +} else {
let's use an if statement for the "/" route, we may add more routes in the future.

2020-10-22 17:44 UTC, utkarsh4321 commented on js/controller/getReposIssues.js
> +const repos = {
Hii @sachin-duhan26 on fetching issues pull request related to the issue is also coming so I will avoid it or keep it.

2020-10-23 11:01 UTC, sachin-duhan26 commented on js/controller/getReposIssues.js
> +const repos = {
I have resolved the merge conflict for you, Cheers 💯

2020-10-23 14:47 UTC, utkarsh4321 commented
Hii @sachin-duhan26 I fix the requested changes can you please review my PR. and if there is any problem tell me so I will try to fix asap.

2020-10-23 17:32 UTC, sachin-duhan26 approved these changes

2020-10-23 17:42 UTC, merged